# Play for db server
- name: first play for conf db servers
  gather_facts: false
  hosts: db_servers
  tasks:
    - name: update apt repo
      ansible.builtin.apt:
        update_cache: yes
      tags: always

    - name: Install Initial Packages for PostgreSQL 15
      ansible.builtin.apt:
        name: dirmngr
      tags: db-v15

    - name: Install cert
      ansible.builtin.apt:
        name: ca-certificates
      tags: db-v15

    - name: Install some packages
      ansible.builtin.apt:
        name: software-properties-common
      tags: db-v15

    - name: Install apt-transport
      ansible.builtin.apt:
        name: apt-transport-https
      tags: db-v15

    - name: Install lsb
      ansible.builtin.apt:
        name: lsb-release
      tags: db-v15

    - name: Install curl
      ansible.builtin.apt:
        name: curl
      tags: db-v15

    - name: execute some shell commands
      ansible.builtin.shell:
        cmd: |
          curl -fSsL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /usr/share/keyrings/postgresql.gpg > /dev/null
          echo deb [arch=amd64,arm64,ppc64el signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main | sudo tee /etc/apt/sources.list.d/postgresql.list
      tags: db-v15

    - name: update apt repo for installation postgres db
      ansible.builtin.apt:
        update_cache: yes  
      tags: db-v15

    - name: install postgres client db packages
      ansible.builtin.apt:
        name: postgresql-client-15
      tags: db-v15

    - name: install postgres db packages
      ansible.builtin.apt:
        name: postgresql-15
      tags: db-v15

    - name: Start service postgresql-15, if not started
      ansible.builtin.service:
        name: postgresql-15
        state: started
        enabled: true
      tags: db-v15

    - name: install postgres 14 client db packages
      ansible.builtin.apt:
        name: postgresql-client-14
      tags: db-v14

    - name: install postgres db 14 packages
      ansible.builtin.apt:
        name: postgresql-14
      tags: db-v14


- name: second playbook
  hosts: web_servers
  gather_facts: false
  tags: web
  tasks:

    - name: update repo 
      ansible.builtin.apt:
        update_cache: yes

    - name: install nginx
      ansible.builtin.apt:
        name: apache2
        state: present


    - name: Copy developers static files
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0755'   
 
